FROM registrycwfisdev.azurecr.io/firestarr/firestarr-app:0.9.5.5 AS firestarr-app-hotfix
ARG VERSION
ENV VERSION=${VERSION}
WORKDIR /appl/firestarr
COPY ./src/py/firestarr/ /appl/firestarr/src/py/firestarr/
COPY ./src/py/cffdrs-ng/NG_FWI.py /appl/firestarr/src/py/cffdrs-ng/
COPY ./src/py/cffdrs-ng/old_cffdrs.py /appl/firestarr/src/py/cffdrs-ng/
COPY ./src/py/cffdrs-ng/util.py /appl/firestarr/src/py/cffdrs-ng/
RUN echo "v0.9.6 is a patch of v0.9.5.5 to fix errors with empty dataframes but not upgrade numpy or anything else" > /appl/firestarr/NOTE.md
RUN echo "v0.9.7 adds ON specific datasources back" >> /appl/firestarr/NOTE.md
RUN echo "v0.9.8 change SourceFireCiffc to use CWFIF WFS" >> /appl/firestarr/NOTE.md
RUN echo "v0.9.9 changed EX status to OUT so old code works on it" >> /appl/firestarr/NOTE.md
RUN echo "v0.9.10 remove --no-retry from options" >> /appl/firestarr/NOTE.md
RUN echo "v0.9.11 burn any touched pixel into raster" >> /appl/firestarr/NOTE.md
RUN echo "v0.9.12 queue recovery message" >> /appl/firestarr/NOTE.md
RUN echo "v0.9.13 ensure submodule init to proper version on build container" >> /appl/firestarr/NOTE.md
RUN echo "v0.9.14 fix ffmc bounds/rounding issue in cffdrs code" >> /appl/firestarr/NOTE.md
RUN echo "v0.9.15 add GROUP_DISTANCE_KM config option" >> /appl/firestarr/NOTE.md
